# Generated by Django 3.1.5 on 2021-01-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminblog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
